import { NextResponse } from 'next/server'

export async function GET() {
 const doctors = [
  {
    id: 1,
    name: "Dr. Anjali Mehta",
    specialty: "Gynacologist",
    location: "Dombivli, Mumbai",
    availability: true,
    availableText: "Available today",
    experience: "As Psychologist Dr das practices about 7+ years…",
    timing: "09:30 AM - 07:00 PM",
    photo: "/doc1.jpeg",
  },
  {
    id: 2,
    name: "Dr. Raj Singh",
    specialty: "Sr. Dermotologist",
    location: "Dombivli, Mumbai",
    availability: true,
    availableText: "Available today",
    experience: "As Psychologist Dr das practices about 7+ years…",
    timing: "09:30 AM - 07:00 PM",
    photo: "/doc2.jpeg",
  },
  {
    id: 3,
    name: "Dr. Prakash Das",
    specialty: "Sr. Psychologist",
    location: "Dombivli, Mumbai",
    availability: true,
    availableText: "Available today",
    experience: "As Psychologist Dr das practices about 7+ years…",
    timing: "09:30 AM - 07:00 PM",
    photo: "/doc3.jpeg",
  },
  {
  id: 4,
  name: "Dr. Sneha Kapoor",
  specialty: "Pediatrician",
  location: "Thane, Mumbai",
  availability: true,
  availableText: "Available today",
  experience: "Has treated children for over 10 years with a caring approach.",
  timing: "10:00 AM - 05:00 PM",
  photo: "doc4.jpeg",
},
{
  id: 5,
  name: "Dr. Karan Malhotra",
  specialty: "Orthopedic Surgeon",
  location: "Andheri, Mumbai",
  availability: false,
  availableText: "Next available tomorrow",
  experience: "Expert in sports injuries and joint replacement surgeries.",
  timing: "11:00 AM - 06:30 PM",
  photo: "/doc5.jpeg",
},
{
  id: 6,
  name: "Dr. Meera Joshi",
  specialty: "ENT Specialist",
  location: "Borivali, Mumbai",
  availability: true,
  availableText: "Available today",
  experience: "Over 8 years in treating ear, nose, and throat disorders.",
  timing: "09:00 AM - 03:00 PM",
  photo: "/doc6.jpeg",
},
{
  id: 7,
  name: "Dr. Raghav Iyer",
  specialty: "Cardiologist",
  location: "Powai, Mumbai",
  availability: true,
  availableText: "Available today",
  experience: "Cardiac expert with more than 12 years in interventional cardiology.",
  timing: "08:30 AM - 02:00 PM",
  photo: "/doc7.jpeg",
},
{
  id: 8,
  name: "Dr. Farah Shaikh",
  specialty: "Dermatologist",
  location: "Mulund, Mumbai",
  availability: false,
  availableText: "Next available in 2 days",
  experience: "Skin care expert with specialization in acne and hair loss treatments.",
  timing: "01:00 PM - 07:00 PM",
  photo: "/doc8.jpeg",
},
{
  id: 9,
  name: "Dr. Vivek Deshmukh",
  specialty: "Neurologist",
  location: "Navi Mumbai",
  availability: true,
  availableText: "Available today",
  experience: "Experienced in treating epilepsy, stroke, and movement disorders.",
  timing: "10:00 AM - 04:00 PM",
  photo: "/doc9.jpeg",
},
{
  id: 10,
  name: "Dr. Aarti Bhonsle",
  specialty: "General Physician",
  location: "Ghatkopar, Mumbai",
  availability: true,
  availableText: "Available today",
  experience: "Over 15 years of experience in general and internal medicine.",
  timing: "09:30 AM - 06:00 PM",
  photo: "/doc10.jpeg",
}

];
  return NextResponse.json(doctors)
}